### ISSUE TITLE
brew complains about plist_options

### ISSUE THREAD

**Issue by dottedmag** [yqrashawn/homebrew-goku#1]
Hello.

Starting recently:
```
% brew update
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the yqrashawn/goku tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/yqrashawn/homebrew-goku/Formula/goku.rb:16
<...>
```

**Comment by NethumL** [comment]
I think it's related to this: Homebrew/homebrew-core#79367. It looks like they're migrating the formulae to `service do` blocks, which are apparently OS agnostic.

I looked into how the others were migrated to `service do` blocks, and I think for goku, this covers almost everything:

```ruby
  service do
    run [opt_bin/"goku"]
    environment_variables GOKU_EDN_CONFIG_FILE: "~/.config/karabiner.edn"
    error_log_path "~/Library/Logs/goku.log"
    log_path "~/Library/Logs/goku.log"
  end
```

I don't know whether it's possible to add the `WatchPaths` option to this `service do` block (I referred to [this part of the documentation](https://docs.brew.sh/Formula-Cookbook#service-block-methods). 

I also don't know how to use the `HOME` environment variable inside this block. It's possible that it can just be used like this:
```ruby
    error_log_path ENV["HOME"]/"Library/Logs/goku.log"
``` 
But I don't know for sure.

Also, I'm not sure about how the `plist_options :manual => "gokuw"` should be in the `service do` block.

**Comment by eugenesvk** [comment]
There doesn't seem to be a watcher in the new services brew block (e.g., the source for the service also doesn't seem to have anything https://github.com/Homebrew/brew/blob/master/Library/Homebrew/service.rb), so we might have to revert this commit https://github.com/yqrashawn/homebrew-goku/commit/89fbfbe339d0fdb7ee511f52bc7ea19597d1f257 and go back to depending on watchexec

I've tried that, but then I couldn't make the new `homebrew.mxcl.goku.plist` work at all, and when I tried to debug it by running `/bin/zsh -c 'exec --allexport gokuw /usr/local/opt/watchexec/bin/watchexec --restart -e edn --watch ~/.config/karabiner.edn /usr/local/opt/goku/bin/goku'`, I  get a `zsh:1: unknown exec flag -\M-[` error

Have you had the watcher service working in the previous version 0.5.0? Or do you have any idea what a proper working homebrew.mxcl.goku.plist would be with a shell command?



FYI my attempt to fix it is here

https://github.com/eugenesvk/homebrew-goku/tree/brew_fix

**Comment by yqrashawn** [comment]
Fixed now, run `brew reinstall yqrashawn/goku/goku` to fix the homebrew service.
